name: strain_library
channels:
  - conda-forge
  - defaults
dependencies:
  - tqdm 
  - numpy
  - pandas 
  - openpyxl 
  - jupyterlab
  - jupyter_http_over_ws 
  - scikit-learn 
  - umap-learn
  - plotly 
  # Doesn't work on M1 Macs from conda: https://github.com/plotly/Kaleido/issues/70
  # - python-kaleido   
  - matplotlib
  - pytest
